/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module myEdge_detector_3 (
    input clk,
    input in,
    output reg out
  );
  
  
  
  reg M_last_d, M_last_q = 1'h0;
  
  always @* begin
    M_last_d = M_last_q;
    
    out = 1'h0;
    M_last_d = in;
    if (in == 1'h1 && M_last_q == 1'h0) begin
      out = 1'h1;
    end
  end
  
  always @(posedge clk) begin
    M_last_q <= M_last_d;
  end
  
endmodule
