/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module ledhelper_1 (
    input [3:0] num,
    output reg [7:0] led
  );
  
  
  
  always @* begin
    led = 8'h00;
    
    case (num)
      1'h0: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h1;
      end
      1'h1: begin
        led[0+0-:1] = 1'h1;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h1;
        led[4+0-:1] = 1'h1;
        led[5+0-:1] = 1'h1;
        led[6+0-:1] = 1'h1;
      end
      2'h2: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h1;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h1;
        led[6+0-:1] = 1'h0;
      end
      2'h3: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h1;
        led[5+0-:1] = 1'h1;
        led[6+0-:1] = 1'h0;
      end
      3'h4: begin
        led[0+0-:1] = 1'h1;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h1;
        led[4+0-:1] = 1'h1;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h0;
      end
      3'h5: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h1;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h1;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h0;
      end
      3'h6: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h1;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h0;
      end
      3'h7: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h1;
        led[4+0-:1] = 1'h1;
        led[5+0-:1] = 1'h1;
        led[6+0-:1] = 1'h1;
      end
      4'h8: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h0;
      end
      4'h9: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h1;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h0;
      end
      4'ha: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h1;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h0;
      end
      4'hb: begin
        led[0+0-:1] = 1'h1;
        led[1+0-:1] = 1'h1;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h0;
      end
      4'hc: begin
        led[0+0-:1] = 1'h1;
        led[1+0-:1] = 1'h1;
        led[2+0-:1] = 1'h1;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h1;
        led[6+0-:1] = 1'h0;
      end
      4'hd: begin
        led[0+0-:1] = 1'h1;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h0;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h1;
        led[6+0-:1] = 1'h0;
      end
      4'he: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h0;
        led[2+0-:1] = 1'h1;
        led[3+0-:1] = 1'h0;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h0;
      end
      4'hf: begin
        led[0+0-:1] = 1'h0;
        led[1+0-:1] = 1'h1;
        led[2+0-:1] = 1'h1;
        led[3+0-:1] = 1'h1;
        led[4+0-:1] = 1'h0;
        led[5+0-:1] = 1'h0;
        led[6+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
